# Generated by Django 4.1 on 2022-09-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cuestionario", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="informacion",
            options={"verbose_name_plural": "Informaciones"},
        ),
    ]
