# Generated by Django 4.1 on 2022-09-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cuestionario", "0002_alter_informacion_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="informacion",
            old_name="resp",
            new_name="respuesta",
        ),
    ]
