# Generated by Django 4.1 on 2022-10-05 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0004_remove_puntaje_usuario_pregunta_puntaje_usuario_resp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alternativa",
            old_name="resp",
            new_name="respuesta",
        ),
        migrations.RenameField(
            model_name="alternativa",
            old_name="resp_correcta",
            new_name="respuesta_correcta",
        ),
    ]
